### ISSUE TITLE
confusing repository names

### ISSUE THREAD

**Issue by bdrees** [googlegenomics/getting-started-with-the-api#5]
One is named "getting_started" and one is named "start_here"!  Please disambiguate, thanks.

**Comment by deflaux** [comment]
Fair point!  "getting_started" is really "getting_started_with_the_api" but let's keep thinking of a brief-yet-clear new name for it.

Will fix - thanks!

**Comment by bdrees** [comment]
Thanks!  Users on the MSSNG project need to go to getting_started.

**Comment by deflaux** [comment]
done, thanks for the feedback!
